# Generated by Django 4.2.3 on 2023-09-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatemodel',
            name='skill',
        ),
        migrations.AddField(
            model_name='candidatemodel',
            name='education',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
