# Generated by Django 4.2.3 on 2023-09-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('candidate', '0007_alter_myappliedjobmodel_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myappliedjobmodel',
            name='jobPost',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobpostmodel'),
        ),
    ]
